branches:
    only:
        - release
dist: focal
sudo: required

before_deploy:
    - git config --local user.name "gon1942"
    - git config --local user.email "gon1942@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag ${TRAVIS_TAG}
deploy:
    provider: releases
    file_glob: true
    file: ./*
    skip_cleanup: true
    draft: true
    on:
        branch: release
    token: $GITHUB_TOKEN
