name: "My CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
    
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        # Alpha Release
        uses: cla-assistant/github-action@v2.0.0-alpha
        env: 
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}          
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_TOKEN }}
        with: 
          path-to-signatures: 'contributions-signatures/cla.json'
          # Add path to the CLA here
          path-to-cla-document: 'https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md'
          branch: 'master'
          allowlist: bot*, George3d6, ZoranPandovski, torrmal, Stpmax, maximlopin, paxcema, mindsdbadmin
          
          custom-notsigned-prcomment: "\n\n요청해 주신 PR을 반영하기 이전에, [Contributor License Agreements](https://ko.wikipedia.org/wiki/%EA%B8%B0%EC%97%AC%EC%9E%90_%EB%9D%BC%EC%9D%B4%EC%84%A0%EC%8A%A4_%EB%8F%99%EC%9D%98)에 동의해 주셔야 합니다. [해당 문서](https://github.com/hamonikr/hamonize/blob/master/cla/HamoniKRCLA_ko.md)를 확인하신 후, 댓글로 아래 문구(I AGREE this CLA)를 남겨주시면 CLA 사인이 완료됩니다.\n\nThank you for your pull request and welcome to our community! We require contributors to sign our [Contributor License Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement). After checking [this document](https://github.com/hamonikr/hamonize/blob/master/cla/HamoniKRCLA_en.md), please leave the following statement(I AGREE this CLA) in the comments to complete the CLA signature."
          custom-pr-sign-comment: 'I AGREE this CLA.'
