name: Generate and Add Hashes to Release Notes

on:
  release:
    types: [published]

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Assuming that the release asset is uploaded and its name is 'your_asset.zip'
      - name: Download release asset
        run: wget https://github.com/gon1942/git_command/archive/refs/tags/v0.0.55.zip

      # Generate SHA256 hash for the asset
      - name: Generate SHA256 hash
        run: sha256sum your_asset.zip > hashes.txt

      # Read hash from hashes.txt
      - name: Read hash
        id: get_hash
        run: echo "HASH_VALUE=$(cat hashes.txt)" >> $GITHUB_ENV

      # Update release notes
      - name: Update release notes with hash
        uses: github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, tag_name } = context.payload.release;
            const release = await github.rest.repos.getReleaseByTag({ owner, repo, tag: tag_name });
            const updated_notes = release.data.body + "\n\nSHA256 hash: " + process.env.HASH_VALUE;
            await github.rest.repos.updateRelease({ owner, repo, release_id: release.data.id, body: updated_notes });
