name: Generate sha256 hashes for release files
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: List current directory
      run: ls -la
    - name: Generate Hashes
      uses: MCJack123/ghaction-generate-release-hashes@v3
      with:
        hash-type: sha1
        file-name: hashes.txt
    - name: 현재 디렉터리 파일 나열
      run: ls -al
    - name: Upload Hashes to release
      uses: actions/upload-artifact@v2
      with:
        name: Asset Hashes
        path: hashes.txt
        overwrite: true
        asset_name: Files-SHA256-Hashes.txt
        tag: ${{ github.ref }}
        
