name: Add License

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Adding License
        uses: dephraiim/license-action@v1
        with:
          LICENSE_TYPE: BSD
          AUTHOR: Ephraim Atta-Duncan
          PROJECT_NAME: ryan test projext
