name: SBOM upload

on:
  workflow_dispatch:
  push:
    branches: ["master"]
env:
  DeleteManifestDirIfPresent: 'true'
  
jobs:
  SBOM-upload:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: write
      actions: write
      statuses: write

    steps:
    - uses: actions/checkout@v3
    - name: Generate SBOM
      # generation command documentation: https://github.com/microsoft/sbom-tool#sbom-generation
      run: |
        # curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        # chmod +x $RUNNER_TEMP/sbom-tool
        # $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn $ -pv 1.0.0 -ps git_command
        curl -Lo ./sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x ./sbom-tool
        ./sbom-tool generate -b . -bc . -pn $ -pv 1.0.0 -ps git_command
        echo "----------------2123123---ls ------"
        ls -al $RUNNER_TEMP
        echo "-------------------ls ------"
        ls -al ./*
        echo "-------------------ls 3------"
        ls -al ./_manifest/spdx_2.2/*
        echo "-------------------ls -2-----"
        ls -al /tmp/

        
    - uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: _manifest/spdx_2.2
        
    # - name: SBOM upload
    #   uses: advanced-security/spdx-dependency-submission-action@v0.0.1
    #   with:
    #     filePath: "./_manifest/spdx_2.2/manifest.spdx.json"
